### ISSUE TITLE
Publish to NPM with proper LICENSE metadata.

### ISSUE THREAD

**Issue by alexkrauss** [faeldt/base64id#6]
The newest version of this package on NPM still specifies "license: none" (https://www.npmjs.com/package/base64id).

Can you publish a new version to NPM which has the proper license tag in package.json (This is already there as of commit 51bc378ee293, but it is not published yet).

Having proper license metadata helps managing large projects with complex dependencies.

**Comment by VyvIT** [comment]
+1

**Comment by tmpvar** [comment]
bump

**Comment by shinichy** [comment]
+1

**Comment by danielstreit** [comment]
+1

**Comment by cheesymoo** [comment]
+1

**Comment by KristianSelnas** [comment]
+1

**Comment by kapouer** [comment]
Please note that the LICENSE file is absent from the published module on npmjs.org.
While the wrong/missing key in package.json isn't really a legal issue, the fact the license is missing from the files when installing through `npm install base64id` can be problematic.

**Comment by edi9999** [comment]
Please add this to npm !

**Comment by Samsy** [comment]
Could this be fixed please ??

**Comment by rogierschouten** [comment]
Please see #8   The package.json uses deprecated constructs

**Comment by darrachequesne** [comment]
Released as `1.0.0`.

**Comment by edi9999** [comment]
Thanks !
